#!/bin/bash
#
# Validation script used to ensure semantic equivalence of the scripts
# produced by the new MakeTestScript program and the old C implementation
# of mts. Depends on the mts/javamts wrapper scripts.
#
# Set the conditional compilation variables in the script generators
# as follows:
#
# EXACT_COMPATIBILITY = true;
# EXACT_COMPATIBILITY_C = true;
# EXACT_COMPATIBILITY_JAVA = false;
#
# This script will then demonstrate that the new MakeTestScript program
# generates scripts that are lexically identical to those generated by
# the old mts program (excepting whitespace variations). A trivial
# inspection of the changes effected by the above conditional compilation
# flags then proves semantic equivalence.
#
# Alex Kinneer
# University of Nebraska - Lincoln
# February 14, 2006

OLD_MTS='/net/frost/export/u3/galileo/aristotle/v3.5.6/bin/sunos5/mts'
NEW_MTS='/net/frost/export/u3/galileo/alex/mts/mts'
SUBJECT_DIR='/net/frost/export/u3/galileo/subjects/internal/c'
REPORT_FILE=`pwd`/c-mts-validate-report.txt

cd ${SUBJECT_DIR}

for SBJ_NAME in *; do
  echo "Checking ${SBJ_NAME}..."

  cd ${SBJ_NAME}/testplans.alt
  
  for VERSION in v[0-9]*; do
    for UNIV in ${VERSION}/*.universe; do
      for TYPE in R D d T; do
        OLD_SCRIPT="${SBJ_NAME}_${TYPE}.old.csh"
        NEW_SCRIPT="${SBJ_NAME}_${TYPE}.new.csh"
        ${OLD_MTS} ".." ${SBJ_NAME} ${UNIV} ${TYPE} ${OLD_SCRIPT} ${SBJ_NAME} "../outputs.alt/"${VERSION}
        ${NEW_MTS} ".." ${SBJ_NAME} ${UNIV} ${TYPE} ${NEW_SCRIPT} ${SBJ_NAME} "../outputs.alt/"${VERSION}
        diff -b ${OLD_SCRIPT} ${NEW_SCRIPT} > /dev/null
        if [ $? -ne 0 ]; then
          echo '[FAIL] '"${SBJ_NAME} : Type ${TYPE} : ${UNIV}" >> ${REPORT_FILE}
          exit
        else
          echo '[PASS] '"${SBJ_NAME} : Type ${TYPE} : ${UNIV}" >> ${REPORT_FILE}
        fi
        rm ${OLD_SCRIPT}
        rm ${NEW_SCRIPT}
      done
    done
  done
      
  cd ${SUBJECT_DIR}
done
