LEVEL = ../..

LIBRARYNAME = Constraints
BUILD_ARCHIVE = 1
LOADABLE_MODULE = 1
# TOOLNAME = solver_test
# LLVMLIBS = LLVMSupport.a LLVMCore.a LLVMBitReader.a LLVMAsmParser.a LLVMAnalysis.a LLVMTransformUtils.a LLVMScalarOpts.a LLVMTarget.a

include $(LEVEL)/Makefile.common
