/* #define FAULTY_F_TW_1 */
/* #define FAULTY_F_KP_1 */
/* #define FAULTY_F_KP_2 */
/* #define FAULTY_F_KP_3 */
/* #define FAULTY_F_KP_4 */
/* #define FAULTY_F_KL_1 */
/* #define FAULTY_F_KL_2 */
/* #define FAULTY_F_KL_3 */
/* #define FAULTY_F_KL_4 */
/* #define FAULTY_F_KL_5 */
