// $ANTLR 2.7.6 (2005-12-22): "STImpL.g" -> "STImpLParser.java"$

/*
 * Copyright (c) 2003-Present Alex Kinneer. All rights reserved.
 *
 * THIS SOFTWARE IS PROVIDED ``AS IS'' AND ANY EXPRESSED OR IMPLIED
 * WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES
 * OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
 * DISCLAIMED.  IN NO EVENT SHALL THE COPYRIGHT HOLDER
 * BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
 * SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
 * LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF
 * USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
 * ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
 * OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT
 * OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF
 * SUCH DAMAGE.
 */

package sir.mts.parser;

public interface STImpLParserTokenTypes {
	int EOF = 1;
	int NULL_TREE_LOOKAHEAD = 3;
	int ASSIGN_VAR = 4;
	int NEWLINE = 5;
	int SET_CLASSPATH = 6;
	// "-P" = 7
	int BEGIN = 8;
	int END = 9;
	// "-I" = 10
	// "-O" = 11
	// "-F" = 12
	int BAR = 13;
	// "-S" = 14
	// "-s" = 15
	int EQ = 16;
	// "-X" = 17
	// "-x" = 18
	// "-C" = 19
	// "-D" = 20
	// "-B" = 21
	// "-A" = 22
	int DATA = 23;
	int WS = 24;
	int FLAG = 25;
	int DATA_ESC = 26;
	int DATA_NO_ESC = 27;
	int ESC = 28;
	int SUBST = 29;
}
