#!/bin/bash
# Run Constant Analyzer Tool

#Store the number of arguments

len=$#

#check the total number of arguments

if [ $len -ne 1 ]; then

echo "Specify the path to source target as the only argument"

fi


/home/user/LLVM/llvm-project/build/bin/pp-trace /home/user/Setup-Documentation/linux-reference/linux-4.14.1/security/apparmor/lsm.c -- -Wp,-MD,/home/user/Setup-Documentation/linux-reference/linux-4.14.1/security/apparmor/.lsm.o.d  -nostdinc -isystem /usr/lib/clang/9/include -I/home/user/Setup-Documentation/linux-reference/linux-4.14.1/arch/x86/include -I/home/user/Setup-Documentation/linux-reference/linux-4.14.1/arch/x86/include/generated  -I/home/user/Setup-Documentation/linux-reference/linux-4.14.1/include -I/home/user/Setup-Documentation/linux-reference/linux-4.14.1/arch/x86/include/uapi -I/home/user/Setup-Documentation/linux-reference/linux-4.14.1/arch/x86/include/generated/uapi -I/home/user/Setup-Documentation/linux-reference/linux-4.14.1/include/uapi -I/home/user/Setup-Documentation/linux-reference/linux-4.14.1/include/generated/uapi -include /home/user/Setup-Documentation/linux-reference/linux-4.14.1/include/linux/kconfig.h -D__KERNEL__ -fno-pie -Wall -Wundef -Wstrict-prototypes -Wno-trigraphs -fno-strict-aliasing -fno-common -fshort-wchar -Werror-implicit-function-declaration -Wno-format-security -std=gnu89 -fno-PIE -mno-sse -mno-mmx -mno-sse2 -mno-3dnow -mno-avx -m64 -falign-jumps=1 -falign-loops=1 -mno-80387 -mno-fp-ret-in-387 -mpreferred-stack-boundary=3 -mskip-rax-setup -mtune=generic -mno-red-zone -mcmodel=kernel -funit-at-a-time -DCONFIG_X86_X32_ABI -DCONFIG_AS_CFI=1 -DCONFIG_AS_CFI_SIGNAL_FRAME=1 -DCONFIG_AS_CFI_SECTIONS=1 -DCONFIG_AS_FXSAVEQ=1 -DCONFIG_AS_SSSE3=1 -DCONFIG_AS_CRC32=1 -DCONFIG_AS_AVX=1 -DCONFIG_AS_AVX2=1 -DCONFIG_AS_AVX512=1 -DCONFIG_AS_SHA1_NI=1 -DCONFIG_AS_SHA256_NI=1 -pipe -Wno-sign-compare -fno-asynchronous-unwind-tables -fno-pie -no-pie -fno-delete-null-pointer-checks -Wno-frame-address -Wno-format-truncation -Wno-format-overflow -Wno-int-in-bool-context -O2 --param=allow-store-data-races=0 -DCC_HAVE_ASM_GOTO -fno-reorder-blocks -fno-ipa-cp-clone -fno-partial-inlining -fno-stack-protector -Wno-unused-but-set-variable -Wno-unused-const-variable -fno-omit-frame-pointer -fno-optimize-sibling-calls -fno-var-tracking-assignments -pg -mfentry -DCC_USING_FENTRY -fno-inline-functions-called-once -Wdeclaration-after-statement -Wno-pointer-sign -fno-strict-overflow -fconserve-stack -Werror=implicit-int -Werror=strict-prototypes -Werror=date-time -Werror=incompatible-pointer-types -Werror=designated-init    -fsanitize=kernel-address -fasan-shadow-offset=0xdff8000000000000 --param asan-stack=1 --param asan-globals=1 --param asan-instrumentation-with-call-threshold=0  -fsanitize-address-use-after-scope   -fsanitize-coverage=trace-pc    -DKBUILD_BASENAME='"lsm"'  -DKBUILD_MODNAME='"apparmor"' -c &> apparmor.pptrace

grep -R "#define" $1 &> apparmor.defines

python organize-pp-trace.py apparmor.defines apparmor.pptrace

/home/user/LLVM/llvm-project/build/bin/constant-analyzer /home/user/Setup-Documentation/linux-reference/linux-4.14.1/security/apparmor/lsm.c -- -Wp,-MD,/home/user/Setup-Documentation/linux-reference/linux-4.14.1/security/apparmor/.lsm.o.d  -nostdinc -isystem /usr/lib/clang/9/include -I/home/user/Setup-Documentation/linux-reference/linux-4.14.1/arch/x86/include -I/home/user/Setup-Documentation/linux-reference/linux-4.14.1/arch/x86/include/generated  -I/home/user/Setup-Documentation/linux-reference/linux-4.14.1/include -I/home/user/Setup-Documentation/linux-reference/linux-4.14.1/arch/x86/include/uapi -I/home/user/Setup-Documentation/linux-reference/linux-4.14.1/arch/x86/include/generated/uapi -I/home/user/Setup-Documentation/linux-reference/linux-4.14.1/include/uapi -I/home/user/Setup-Documentation/linux-reference/linux-4.14.1/include/generated/uapi -include /home/user/Setup-Documentation/linux-reference/linux-4.14.1/include/linux/kconfig.h -D__KERNEL__ -fno-pie -Wall -Wundef -Wstrict-prototypes -Wno-trigraphs -fno-strict-aliasing -fno-common -fshort-wchar -Werror-implicit-function-declaration -Wno-format-security -std=gnu89 -fno-PIE -mno-sse -mno-mmx -mno-sse2 -mno-3dnow -mno-avx -m64 -falign-jumps=1 -falign-loops=1 -mno-80387 -mno-fp-ret-in-387 -mpreferred-stack-boundary=3 -mskip-rax-setup -mtune=generic -mno-red-zone -mcmodel=kernel -funit-at-a-time -DCONFIG_X86_X32_ABI -DCONFIG_AS_CFI=1 -DCONFIG_AS_CFI_SIGNAL_FRAME=1 -DCONFIG_AS_CFI_SECTIONS=1 -DCONFIG_AS_FXSAVEQ=1 -DCONFIG_AS_SSSE3=1 -DCONFIG_AS_CRC32=1 -DCONFIG_AS_AVX=1 -DCONFIG_AS_AVX2=1 -DCONFIG_AS_AVX512=1 -DCONFIG_AS_SHA1_NI=1 -DCONFIG_AS_SHA256_NI=1 -pipe -Wno-sign-compare -fno-asynchronous-unwind-tables -fno-pie -no-pie -fno-delete-null-pointer-checks -Wno-frame-address -Wno-format-truncation -Wno-format-overflow -Wno-int-in-bool-context -O2 --param=allow-store-data-races=0 -DCC_HAVE_ASM_GOTO -fno-reorder-blocks -fno-ipa-cp-clone -fno-partial-inlining -fno-stack-protector -Wno-unused-but-set-variable -Wno-unused-const-variable -fno-omit-frame-pointer -fno-optimize-sibling-calls -fno-var-tracking-assignments -pg -mfentry -DCC_USING_FENTRY -fno-inline-functions-called-once -Wdeclaration-after-statement -Wno-pointer-sign -fno-strict-overflow -fconserve-stack -Werror=implicit-int -Werror=strict-prototypes -Werror=date-time -Werror=incompatible-pointer-types -Werror=designated-init    -fsanitize=kernel-address -fasan-shadow-offset=0xdff8000000000000 --param asan-stack=1 --param asan-globals=1 --param asan-instrumentation-with-call-threshold=0  -fsanitize-address-use-after-scope   -fsanitize-coverage=trace-pc    -DKBUILD_BASENAME='"lsm"'  -DKBUILD_MODNAME='"apparmor"' -c &> apparmor.constants
